imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        handler_id:  ~
        storage_id: session.storage.filesystem
        name: MOCKSESSID
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

liip_functional_test:
    command_verbosity: debug
    command_decoration: true
    cache_sqlite_db: false
    authentication:
        username: "admin"
        password: "admin"

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_sqlite
                path:     %kernel.cache_dir%/test.db